# Site
name: "ybogomolov.me"
description: "Yuriy Bogomolov's personal blog"
meta_description: "Yuriy Bogomolov's personal blog"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl: /
include: ["_pages"]
permalink: /:title
google_analytics: G-N46PTJBXLE

# Authors
authors:
  yuriy:
    name: Yuriy
    display_name: Yuriy Bogomolov
    gravatar: e3309c2e09d9aa66632ba5811567e9eb
    email: yuriy.bogomolov@gmail.com
    web: https://ybogomolov.me
    twitter: https://twitter.com/YuriyBogomolov
    description: "Functional programmer, speaker & author"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-spaceship

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge

excerpt_separator: <!--more-->

exclude:
  - dev
